### ISSUE TITLE
Estimated pressure calculation

### ISSUE THREAD

**Issue by mycarda** [einergehtnochrein/ra-firmware#1]
The estimated pressure calculation on
https://github.com/einergehtnochrein/ra-firmware/blob/f42df782498a040b144ce2f7d86413024b962fa9/src/rs41/rs41gps.c#L43
gives ten times the expected pressure for an RS41 with no pressure sensor.

The code uses 1013.25f in the calculation but (according to Google) the average pressure at sea level is 101.325 kilopascals.

**Comment by mycarda** [comment]
My previous comment might be a mistake by me getting confused between kPa and hPa and I think my confusion comes from https://github.com/einergehtnochrein/ra-firmware/blob/f42df782498a040b144ce2f7d86413024b962fa9/src/rs41/rs41metrology.c#L245 where 30.0 is the assumed pressure if the pressure cannot be estimated. Is the value 30.0 in kPa or hPa?

**Comment by einergehtnochrein** [comment]
The value 30.0 is in hPa.

I think I will take up that issue and be more explicit with physical units in the future. An extension like "p_hPa" to the variable name would have left no doubt.
